name: Harvard-interview-homework
channels:
  - defaults
  - conda-forge
  - bioconda
  - pypi
dependencies:
  - python=3.11.0 
  - python-duckdb=0.10.2
  - numpy=1.23.5 
  - pandas=2.1.4 
  - pip=24.0 
  - requests==2.31.0
  - pip:
    - hydra-core==1.3.2 
    - snakemake==8.11.3